management:
  endpoints:
    jmx:
      exposure:
        include: info,health,beans,metrics,endpoints,mappings
    web:
      exposure:
        include: health,info,prometheus,metrics

server:
  port: 12037
logging:
  level:
    io:
      micrometer: DEBUG