server:
  port: 12035
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  level:
    org:
      springframework:
        security: DEBUG
