#Public
http://localhost:8080/bieres


###

# Prive
POST http://localhost:8080/bieres
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Type: application/json

{"nom":"Paix Dieu","degres":10}

###
# Prive Mauvais mot de passe
POST http://localhost:8080/bieres
Authorization: Basic dXNlcjpwYXNzd29yZDI=
Content-Type: application/json

{"nom":"Desperados","degres":3.4}



